### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) (feel free to change it) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] Show a preview of the dating profile with rendered HTML (e.g. `<em>hella charming</em>` should appear as _hella charming_)
- [x] Also show the raw, generated HTML inside the `<pre><code></code></pre>` elements (e.g. `<em>hella charming</em>` should appear as `<em>hella charming</em>`)
- [x] Both the preview and raw HTML should update live as the user enters their information
- [x] All JavaScript is in a separate `.js` file
- [x] There are no linting errors in your JavaScript (this will also be expected for all future projects)

**Comment by chrisvfritz** [comment]
Looks pretty good! 👍  I just see a couple areas for improvement:

### Links to email address and phone number

The `href` attributes for `a` elements literally contain the text `EMAIL_ADDRESS` and `PHONE_NUMBER` instead of the email and phone users enter. 

### Indentation of multi-line statements

I really like how you've formatted the string similar to how you would format real HTML! 🙂  This makes it much easier to read. However, there's one step further you can take. Instead of having every line of this statement on the same indentation level, like this:

``` js
preview.innerHTML =
'<h1>Hi my name is ' + fullName + '!</h1>' +
'<p>' + description + '</p>' +
'<p>' +
'  If you\'re interested in a date, you can email me at' +
'  <a href="mailto:EMAIL_ADDRESS" target="_blank">' + email + '</a>' +
'  or give me a call at' +
'  <a href="tel:PHONE_NUMBER" target="_blank">' + phoneNumber + '</a>.' +
'</p>'
```

It's generally better to indent related lines, like this:

``` js
preview.innerHTML =
  '<h1>Hi my name is ' + fullName + '!</h1>' +
  '<p>' + description + '</p>' +
  '<p>' +
  '  If you\'re interested in a date, you can email me at' +
  '  <a href="mailto:EMAIL_ADDRESS" target="_blank">' + email + '</a>' +
  '  or give me a call at' +
  '  <a href="tel:PHONE_NUMBER" target="_blank">' + phoneNumber + '</a>.' +
  '</p>'
```

Then you can tell at a glance that every line of that string is indeed related to that first line. Does that make sense?

### Building the same string twice

It looks like you're building the same HTML string twice, which makes the code a little more difficult to maintain. The reason is, whenever you make a change, you'll have to make it _twice_. If you forget, that's a bug. 🙈  

Instead, I recommend assigning the string to a variable first so you can reuse it. For example, instead of:

``` js
a = 'a string that you want to use more than once'
b = 'a string that you want to use more than once'
```

You'd have:

``` js
var text = 'a string that you want to use more than once'
a = text
b = text
```

---

Let me know if you have any questions. 😺

**Comment by harr1193** [comment]
Fixed the errors I had

**Comment by chrisvfritz** [comment]
Looks fantastic! 🎉 🚀 :shipit: 🎈
